name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  go_router: ^9.0.3
  url_launcher: ^6.1.12

dev_dependencies:
  austerity: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
